name: Atualizar Promocoes

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar robo
        run: node robo.js

      - name: Salvar
        run: |
          git config user.name "bot"
          git config user.email "bot@email.com"
          git add .
          git commit -m "Atualizando promoções reais"
          git push
